### ISSUE TITLE
Add support to mass management

### ISSUE THREAD

**Issue by FlavioF** [tfsoares/maven-smart-builder#1]
Hi,

What do you think about adding support to run configurable commands in all projects of the list (like changing git branch, mvn clean install, etc).

**Comment by tfsoares** [comment]
Hi,

Yes! That would be a great idea! I'll try to do it as soon as I can. Thanks for the input.

**Comment by tfsoares** [comment]
Hi again,

You can now do what you asked as long as you edit the script and add the commands you want to use `COMMAND_OPTIONS` array.
